### ISSUE TITLE
object detection test example?

### ISSUE THREAD

**Issue by zyc4me** [amirgholami/ZeroQ#1]

**Comment by Zhen-Dong** [comment]
Thanks for your interest in our work!
We are working on releasing the object detection part.
As we mentioned in the paper, typically you can extract the backbone of the RetinaNet and compute the Distilled data, and then you can compute the sensitivity based on that and perform the zero-shot quantization.

**Comment by amirgholami** [comment]
We have added the object detection code. Please see https://github.com/amirgholami/ZeroQ/tree/master/detection
