### ISSUE TITLE
Reproduction and Auto-Mixed Quantization?

### ISSUE THREAD

**Issue by xieydd** [amirgholami/ZeroQ#10]
Hey, Thanks for your great work.
When i want to reproduce your result, i get a wired result. In classification task on imagenet, here is my result:
```
mobilenetv2 36.5%
shufflenet 32.12%
resnet50 38.83%
resnet18 35.7%
```
I used pytorch 1.5 for Test. When i test resnet20_cifar10, looks normal `93.88%`.
Another question is when auto-mixed quantization version will release?
Anybody help me  @amirgholami @yaohuicai @Zhen-Dong

**Comment by amirgholami** [comment]
I just re-tested the code with Pytorch 1.5, Cuda 10.1, and Python 3.8 and got the same results as reported in [README](https://github.com/amirgholami/ZeroQ).

We plan to open source the mixed precision along with some new features soon.

**Comment by xieydd** [comment]
@amirgholami I re-download imagenet val dataset, i got the right result, tks.
