### ISSUE TITLE
Questions about quantization

### ISSUE THREAD

**Issue by jakc4103** [amirgholami/ZeroQ#2]
Hi, thanks for the great paper and codes. I have 2 questions about quantization in the paper:
1. Is the quantization used in paper per-channel or per-tensor? (In [quant_utils.py](https://github.com/amirgholami/ZeroQ/blob/master/utils/quantization_utils/quant_utils.py) it seems to be per-channel)
2. Is the results tested on true int8 inference? or only tested with fake quantization?

Thanks again!

**Comment by yaohuicai** [comment]
Thank you for your interest in our paper! 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yaohuicai** [comment]
Thank you for your interest in our paper. As for the two questions:
1. Yes, we are using per-channel quantization.
2. I am not quite sure what true quantization and fake quantization are referring to in your context. It would be good if you can be more specific.

**Comment by jakc4103** [comment]
@yaohuicai tks for reply!  
For fake quantization, I mean 32 bits floating points with quant-dequant operation to simulate 8 bit integer, the computation is done using FP32; instead of using Int8 integer arithmetics (true Int8 i refers to).

I think the difference is for some operations, residual connections for example, true Int8 arithmetics needs to quantize activation back to Int8 again to prevent overflow since it needs all tensor stored in Int8 tensor.

**Comment by yaohuicai** [comment]
Thank you for your clarification. Our implementation is in _fake quantization_ then, following the convention of current quantization implementation.

**Comment by jakc4103** [comment]
Got it, tks for the great work and reply!

**Comment by hengck23** [comment]
@yaohuicai 

if you have done additional experiments, i would like to know  the performance of 'per tensor quantization'  versus 'per channel quantization'.

Thank you very much.
