### ISSUE TITLE
Reproduce Mixed Quantization Results on paper 

### ISSUE THREAD

**Issue by ckddls1321** [amirgholami/ZeroQ#3]
Hello, it's good to see greatest paper among the quantization methods. 
Really easy to reproduce, also really efficient algorithms without any re-training or validation calibration.

By the way, I have several questions following the paper.
1) Is there any plan to release mixed quantization?

To Reproduce mixed quantization method for paper - Pareto frontier
1) Measure Sensitivity with model size constraints
2) Grouping alpha block of network and select each top-k configuration
3) Solve optimization with DP table(t*alpha) based on sensitivity cost?

Thank you again.

**Comment by amirgholami** [comment]
Hello, many thanks for reaching out and for your interest in our work. Yes we plan to clean the code and release the mixed-precision code soon. 

For the mixed precision Pareto Frontier, note that the model size needs to split into bins. There are also more steps between 2 and 3 in your items. I suggest that you please have a look at [section A of the appendix](https://arxiv.org/pdf/2001.00281.pdf)

**Comment by ckddls1321** [comment]
Thank you I will have a look at section A more.
