### ISSUE TITLE
How is the Mixed Precision bit setting is automated?

### ISSUE THREAD

**Issue by joyalbin** [amirgholami/ZeroQ#7]
Hi,

This solution looks very interesting and getting impressive results on the quantization models.
Thank you so much for sharing the solution.

I have a small confusion in the source code.
I could see, fixed bit precision of 8 bit for weight and activation in the source code.
But couldn't see the method to get exact bit precision configuration for each layer in NN model.
Could you please point me exactly where is this logic incorporated in the source code?

Regards,
Albin

**Comment by amirgholami** [comment]
Hi, 

Many thanks for your interest. The current branch only includes 8-bit quantization. We plan to release the mixed precision code with some new features in the near future.

Best,
