### ISSUE TITLE
Is the proposed method a Offline quantization or Run-time quantization?

### ISSUE THREAD

**Issue by tejpratapgit** [amirgholami/ZeroQ#8]
Dear Author,
Thank you for the great work!!. We are able to successfully run your code. From our observation we noted that the proposed method is a "Run-time-quantization" method which means the quantization of weights, and activations happen during inference time for each layer as opposed to "Offline-Quantization" method where in the stored quantized weights and activations are used during the inference stage. 

During the inference when we call the test(quantized_model, test_loader) in uniformtest.py #114
we observe that in Quant_Conv2d() of quant_modules.py #131 the control flow is always going to if not self.full_precision_flag: in Forward() #169 but not to the else part.

If it not a Run-time quantization method then how are we making use of stored weights and activation ranges quantized using distillation data. In such case we expect the control flow should reach the else: part of forward() call.  Please clarify.

Regards,
Tej.

**Comment by tejpratapgit** [comment]
We found the answer from your code base. Thank you.

**Comment by thuyngch** [comment]
Hi @tejpratapgit ,
How can we export the weight to .pth file so that we could use the exported weight for inference?
